/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import Danhsach.ListDanhSach;
import HoaDon.HoaDon;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.ArrayList;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import javax.swing.table.TableModel;
/**
 *
 * @author 1102l
 */
public class HoaDonJPN extends javax.swing.JPanel {
    String gender;
    String filename = null;
     /**
     * Creates new form listDS
     */
    public HoaDonJPN() {
        initComponents();
        show_user();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtHoten = new javax.swing.JTextField();
        txtmaHD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        rdDa = new javax.swing.JRadioButton();
        rdChua = new javax.swing.JRadioButton();
        txtMaPhong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_List = new javax.swing.JTable();

        setBackground(java.awt.Color.black);
        setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.orange, 2));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(java.awt.Color.orange);
        jLabel1.setText("Họ tên");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(java.awt.Color.orange);
        jLabel2.setText("Mã hóa đơn");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(java.awt.Color.orange);
        jLabel3.setText("Ngày lập hóa đơn");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(java.awt.Color.orange);
        jLabel5.setText("Tình Trạng");

        rdDa.setBackground(new java.awt.Color(0, 0, 0));
        rdDa.setForeground(java.awt.Color.orange);
        rdDa.setText("Đã ");

        rdChua.setBackground(new java.awt.Color(0, 0, 0));
        rdChua.setForeground(java.awt.Color.orange);
        rdChua.setText("Chưa ");
        rdChua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdChuaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(java.awt.Color.orange);
        jLabel4.setText("Mã phòng");

        saveBtn.setBackground(java.awt.Color.orange);
        saveBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveBtn.setText("Lưu");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        jButton2.setBackground(java.awt.Color.orange);
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(java.awt.Color.orange);
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Xóa");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTable1_List.setBackground(java.awt.Color.orange);
        jTable1_List.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "ID", "Họ tên", "Mã Phòng", "Thời gian ", "Tình trạng"
            }
        ));
        jTable1_List.setColumnSelectionAllowed(true);
        jTable1_List.setSelectionBackground(java.awt.Color.orange);
        jTable1_List.setSelectionForeground(java.awt.Color.orange);
        jTable1_List.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_ListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_List);
        jTable1_List.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtHoten, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmaHD, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rdDa)
                        .addGap(18, 18, 18)
                        .addComponent(rdChua)))
                .addContainerGap(86, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(saveBtn)
                .addGap(20, 20, 20)
                .addComponent(jButton2)
                .addGap(20, 20, 20)
                .addComponent(jButton3)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(rdDa)
                    .addComponent(rdChua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(saveBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rdChuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdChuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdChuaActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed

        try {

                String url = "jdbc:sqlserver://localhost:1433;databaseName=QLCC;"
                    + "encrypt=true;trustServerCertificate=true;sslProtocol=TLSv1.2";
            String username = "sa";
            String password = "12345";
            
            Connection con = DriverManager.getConnection(url,username,password);
            String query = "INSERT INTO HoaDon(maHD, hotenchuho, canho, time, trangthai) VALUES(?, ?, ?, ?, ?)";
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, txtmaHD.getText());
            ps.setString(2, txtHoten.getText());
            ps.setString(3, txtMaPhong.getText());
            ps.setString(4, txtTime.getText());
            if (rdDa.isSelected()) {
                gender = "Đã thanh toán";
            } else {
                gender = "Chưa thanh toán";
            }
            ps.setString(5, gender);    
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Insert Successfully");
            DefaultTableModel model = (DefaultTableModel) jTable1_List.getModel();
            model.setRowCount(0);
            show_user();
        } catch (Exception e) {
            e.printStackTrace();
        }

        }

         public ArrayList<HoaDon> userList() {
        ArrayList<HoaDon> userList = new ArrayList<>();

        try {
            String url = "jdbc:sqlserver://localhost:1433;databaseName=QLCC;"
                    + "encrypt=true;trustServerCertificate=true;sslProtocol=TLSv1.2";
            String username = "sa";
            String password = "12345";
            
            Connection con = DriverManager.getConnection(url,username,password);
            String query1 = "SELECT * FROM HoaDon;";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            HoaDon lids;
            while (rs.next()) {

                lids = new HoaDon(rs.getInt("stt"),rs.getString("maHD"), rs.getString("hotenchuho"), rs.getString("canho"), rs.getDate("time"), rs.getString("trangthai"));
                userList.add(lids);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return userList;

        }

        public void show_user() {
        ArrayList<HoaDon> list = userList();
        DefaultTableModel model = (DefaultTableModel) jTable1_List.getModel();
        Object[] row = new Object[6];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getStt();
            row[1] = list.get(i).getMaHD();
            row[2] = list.get(i).getHotenchuho();
            row[3] = list.get(i).getCanho();
            row[4] = list.get(i).getTime();
            row[5] = list.get(i).getTrangthai();
            
            model.addRow(row);
            }

    }//GEN-LAST:event_saveBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       try {
            String url = "jdbc:sqlserver://localhost:1433;databaseName=QLCC;"
                    + "encrypt=true;trustServerCertificate=true;sslProtocol=TLSv1.2";
            String username = "sa";
            String password = "12345";
            
            Connection con = DriverManager.getConnection(url,username,password);
            int row = jTable1_List.getSelectedRow();
            String value = (jTable1_List.getModel().getValueAt(row, 0).toString());
            String query = "Update HoaDon SET maHD = ? , hotenchuho = ? , canho = ? , time = ? , trangthai = ? where stt =" + value;
            PreparedStatement ps = con.prepareStatement(query);
            ps.setString(1, txtmaHD.getText());
            ps.setString(2, txtHoten.getText());
            ps.setString(3, txtMaPhong.getText());
            ps.setString(4, txtTime.getText());
            if (rdDa.isSelected()) {
                gender = "Đã thanh toán";
            } else {
                gender = "Chưa thanh toán";
            }
            ps.setString(5, gender);    
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Update Successfully");
            DefaultTableModel model = (DefaultTableModel)jTable1_List.getModel();
            model.setRowCount(0);
            show_user();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int opt = JOptionPane.showConfirmDialog(null, "Bạn đã chắc chắn xóa ?","Delete",JOptionPane.YES_NO_OPTION);
        if(opt ==0){
        
        try {
            String url = "jdbc:sqlserver://localhost:1433;databaseName=QLCC;"
                    + "encrypt=true;trustServerCertificate=true;sslProtocol=TLSv1.2";
            String username = "sa";
            String password = "12345";
            
            Connection con = DriverManager.getConnection(url,username,password);
            int row = jTable1_List.getSelectedRow();
            String value = (jTable1_List.getModel().getValueAt(row, 0).toString());
            String query = "Delete From HoaDon where stt =" + value;
            PreparedStatement ps = con.prepareStatement(query);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Delete Successfully");
            DefaultTableModel model = (DefaultTableModel)jTable1_List.getModel();
            model.setRowCount(0);
            show_user();

        } catch (Exception e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1_ListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_ListMouseClicked
        int i = jTable1_List.getSelectedRow();
        TableModel model = jTable1_List.getModel();
        txtmaHD.setText(model.getValueAt(i, 1).toString());
        txtHoten.setText(model.getValueAt(i, 2).toString());
        txtMaPhong.setText(model.getValueAt(i, 3).toString());
        txtTime.setText(model.getValueAt(i,4).toString());
        gender = model.getValueAt(i, 5).toString();
        if (gender.equals("Chưa thanh toán")) {
                rdChua.setSelected(true);
            } else {
                rdDa.setSelected(true);
            }        
    }//GEN-LAST:event_jTable1_ListMouseClicked

 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1_List;
    private javax.swing.JRadioButton rdChua;
    private javax.swing.JRadioButton rdDa;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTextField txtHoten;
    private javax.swing.JTextField txtMaPhong;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtmaHD;
    // End of variables declaration//GEN-END:variables
}
